---

- name: Add email address to root crontab (MAILTO)
  community.general.cronvar:
    name: MAILTO
    value: "{{ my_email }}"
  tags: [cron]

- name: Add FROM email address to root crontab (MAILFROM)
  community.general.cronvar:
    name: MAILFROM
    value: "{{ my_email }}"
  tags: [cron]

- name: Add email address to user crontab (MAILTO)
  community.general.cronvar:
    name: MAILTO
    value: "{{ my_email }}"
    user: rlommers
  tags: [cron]

- name: Add FROM email address to user crontab (MAILFROM)
  community.general.cronvar:
    name: MAILFROM
    value: "{{ my_email }}"
    user: rlommers
  tags: [cron]

- name: Apply node-specific tasks for services VM
  ansible.builtin.include_tasks: vm-services.yml
  when: ansible_facts['nodename'] == "services"

- name: Apply node-specific tasks for nas-nijmegen VM
  ansible.builtin.include_tasks: vm-nas-nijmegen.yml
  when: ansible_facts['nodename'] == "nas-nijmegen"
