---

- name: Create /srv/local directory
  ansible.builtin.file:
    path: /srv/local
    state: directory
    owner: "rlommers"
    group: "rlommers"
  tags: [nfs, system]

- name: Create /srv/nas directory
  ansible.builtin.file:
    path: /srv/nas
    state: directory
    owner: "rlommers"
    group: "rlommers"
  tags: [nfs, system]

# NFS SERVER PARTS
####################################################
- name: Install NFS server packages
  ansible.builtin.apt:
    name:
      - nfs-kernel-server
      - nfs-common
    state: present
    update_cache: true
  tags: [packages, nfs]

- name: Configure NFS exports
  ansible.builtin.template:
    src: exports-nas-nijmegen.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
    force: true
  tags: [nfs]

- name: Apply NFS exports
  ansible.builtin.command: exportfs -ra
  changed_when: false
  tags: [nfs]

- name: Ensure NFS server service is started
  ansible.builtin.service:
    name: nfs-server
    state: started
    enabled: true
  tags: [nfs]

# CRONJOB PARTS

- name: Cron job for scheduled file deletions
  ansible.builtin.cron:
    name: "crontab for scheduled file deletions"
    # daily at 00:00
    minute: "0"
    hour: "0"
    day: "*"
    weekday: "*"
    user: rlommers
    job: "/home/rlommers/scripts/scheduled-deletions.sh"
  tags: [cron, backup]

- name: Cron job for purging and checking Hetzner backups
  ansible.builtin.cron:
    name: "crontab for purging and checking hetzner"
    # every Sunday at 06:00
    minute: "0"
    hour: "6"
    day: "*"
    weekday: "0"
    user: rlommers
    job: "/home/rlommers/scripts/restic-backup-hetzner.sh forget_and_check && curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/{{ hc_purge_hetzner_uuid }}"
  tags: [cron, backup]

- name: Cron job for backing up to Edwin
  ansible.builtin.cron:
    name: "crontab for backing up to edwin"
    # daily at 03:30
    minute: "30"
    hour: "3"
    day: "*"
    weekday: "*"
    job: "/home/rlommers/scripts/restic-backup-edwin.sh backup quiet && curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/{{ hc_backup_edwin_uuid }}"
    user: rlommers
  tags: [cron, backup]
