---

# chsh -s /bin/zsh rlommers
- name: Ensure default shell is /bin/zsh
  become: true
  ansible.builtin.user:
    name: "rlommers"
    shell: /bin/zsh
  tags: [dotfiles]

- name: Ensure .config directory exists
  become: false
  ansible.builtin.file:
    path: "/home/rlommers/.config"
    state: directory
    mode: '0755'
  tags: [dotfiles]

- name: Clone dotfiles repository
  become: false
  ansible.builtin.git:
    repo: "git@github.com:rogierlommers/dotfiles.git"
    dest: "/home/rlommers/dotfiles"
    force: true
    accept_hostkey: true
  tags: [dotfiles]

# git clone --depth 1 https://github.com/mattmc3/antidote.git ~/.antidote
- name: Clone antidote zsh plugin manager
  become: false
  ansible.builtin.git:
    repo: "https://github.com/mattmc3/antidote.git"
    dest: "/home/rlommers/.antidote"
    depth: 1
  tags: [dotfiles]

# ln -s ~/dotfiles/dotfiles/scripts ~/scripts
- name: Symlink scripts directory
  become: false
  ansible.builtin.file:
    src: "/home/rlommers/dotfiles/dotfiles/scripts"
    dest: "/home/rlommers/scripts"
    state: link
    force: true
  tags: [dotfiles]

# ln -s ~/dotfiles/dotfiles/tmux/.tmux.conf ~/.tmux.conf
- name: Symlink tmux.conf
  become: false
  ansible.builtin.file:
    src: "/home/rlommers/dotfiles/dotfiles/tmux/.tmux.conf"
    dest: "/home/rlommers/.tmux.conf"
    state: link
    force: true
  tags: [dotfiles]

# ln -s ~/dotfiles/dotfiles/zsh/.zshrc_linux ~/.zshrc
- name: Symlink .zshrc
  become: false
  ansible.builtin.file:
    src: "/home/rlommers/dotfiles/dotfiles/zsh/.zshrc_linux"
    dest: "/home/rlommers/.zshrc"
    state: link
    force: true
  tags: [dotfiles]

# ln -s ~/dotfiles/dotfiles/zsh/.zsh_aliases.sh ~/.zsh_aliases.sh
- name: Symlink .zsh_aliases.sh
  become: false
  ansible.builtin.file:
    src: "/home/rlommers/dotfiles/dotfiles/zsh/.zsh_aliases.sh"
    dest: "/home/rlommers/.zsh_aliases.sh"
    state: link
    force: true
  tags: [dotfiles]

# ln -s ~/dotfiles/dotfiles/zsh/.zsh_functions.sh ~/.zsh_functions.sh
- name: Symlink .zsh_functions.sh
  become: false
  ansible.builtin.file:
    src: "/home/rlommers/dotfiles/dotfiles/zsh/.zsh_functions.sh"
    dest: "/home/rlommers/.zsh_functions.sh"
    state: link
    force: true
  tags: [dotfiles]

# ln -s ~/dotfiles/dotfiles/zsh/.zsh_plugins.txt ~/.zsh_plugins.txt
- name: Symlink .zsh_plugins.txt
  become: false
  ansible.builtin.file:
    src: "/home/rlommers/dotfiles/dotfiles/zsh/.zsh_plugins.txt"
    dest: "/home/rlommers/.zsh_plugins.txt"
    state: link
    force: true
  tags: [dotfiles]

# ln -s ~/dotfiles/dotfiles/zsh/.zsh_config.sh ~/.zsh_config.sh
- name: Symlink .zsh_config.sh
  become: false
  ansible.builtin.file:
    src: "/home/rlommers/dotfiles/dotfiles/zsh/.zsh_config.sh"
    dest: "/home/rlommers/.zsh_config.sh"
    state: link
    force: true
  tags: [dotfiles]

# ln -s ~/dotfiles/dotfiles/starship/config.toml ~/.config/starship.toml
- name: Symlink starship config
  become: false
  ansible.builtin.file:
    src: "/home/rlommers/dotfiles/dotfiles/starship/config.toml"
    dest: "/home/rlommers/.config/starship.toml"
    state: link
    force: true
  tags: [dotfiles]

# ln -s ~/dotfiles/dotfiles/ripgrep/.ripgrep.conf ~/.ripgrep.conf
- name: Symlink .ripgrep.conf
  become: false
  ansible.builtin.file:
    src: "/home/rlommers/dotfiles/dotfiles/ripgrep/.ripgrep.conf"
    dest: "/home/rlommers/.ripgrep.conf"
    state: link
    force: true
  tags: [dotfiles]

# ln -s ~/dotfiles/dotfiles/mc/ini ~/.config/mc/ini
- name: Symlink ini file for Midnight Commander
  become: false
  ansible.builtin.file:
    src: "/home/rlommers/dotfiles/dotfiles/mc/ini"
    dest: "/home/rlommers/.config/mc/ini"
    state: link
    force: true
  tags: [dotfiles]

- name: Add scripts directory to PATH
  become: true
  ansible.builtin.copy:
    dest: /etc/profile.d/custom-path.sh
    content: 'PATH=$PATH:/home/rlommers/scripts'
  tags: [dotfiles, system]
