---

- name: Install ssmtp package
  ansible.builtin.apt:
    name: ssmtp
    state: present
  tags: [packages, ssmtp]

- name: Write ssmtp.conf configuration
  ansible.builtin.template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
  tags: [ssmtp]
