# unban ip: sudo fail2ban-client set sshd unbanip 192.168.1.222
# check banned clients: sudo fail2ban-client status sshd

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true
  tags: [packages, fail2ban, security]

- name: Install custom fail2ban jail configuration
  ansible.builtin.template:
    src: customisation.local.j2
    dest: /etc/fail2ban/jail.d/customisation.local
  notify: Restart fail2ban
  tags: [fail2ban, security]
