---
- name: Update apt cache and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
  tags: [packages, system]

- name: Install essential tools
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - restic
      - tmux
      - jq
      - gnupg
      - lsb-release
      - zsh
      - starship
      - curl
      - git
      - vim
      - htop
      - sudo
      - net-tools
      - mc
      - cron
    state: present
  tags: [packages]

- name: Set timezone to Europe/Amsterdam
  community.general.timezone:
    name: Europe/Amsterdam
  tags: [system]

- name: Set git alias st to status
  community.general.git_config:
    name: alias.st
    scope: global
    value: status
  tags: [dotfiles]

- name: Set git default editor to vim
  community.general.git_config:
    name: core.editor
    scope: global
    value: vim
  tags: [dotfiles]
